version: '3'

services:
  dbgg2:
    image: mysql:5.7.34
    command: --innodb-use-native-aio=0
    container_name: db-gg2
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gg2db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - gg2net

  nodegg2:
    build:
      context: ./node
    image: gihovani/node-gg2
    container_name: node-gg2
    entrypoint: dockerize -wait tcp://db-gg2:3306 -timeout 20s /usr/src/app/docker-entrypoint.sh node index.js
    tty: true
    volumes:
      - ./node/:/usr/src/app
    networks:
      - gg2net
    depends_on:
      - dbgg2

  nginxgg2:
    build:
      context: ./nginx
    image: gihovani/nginx-gg2
    container_name: nginx-gg2
    tty: true
    ports:
      - 8080:80
    networks:
      - gg2net
    depends_on:
      - nodegg2

networks:
  gg2net:
    driver: bridge
